### ISSUE TITLE
Add more input types besides text and dropdown

### ISSUE THREAD

**Issue by khaledmashaly** [activepieces/connectors#6]
#### Suggested `Input` types
- `ShortTextInput`: a single-line string, e.g. an access token.
- `LongTextInput`: a multi-line string, e.g. a chat message or a shopping item description.
- `SelectInput`: similar to a `ShortTextInput` but value is chosen from a list of provided strings.
- `IntegerInput`: for example a UNIX epoch.
- `BooleanInput`: true or false

These types will cover the Slack API methods: [`chat.postMessage`][slack-chat-post], [`chat.scheduleMessage`][slack-chat-sch], [`chat.scheduledMessages.list`][slack-chat-sch-list], which will be used for the manual Slack connector implementation.

Other complicated input types like OAuth-related inputs will be implemented when needed.

[slack-chat-post]: https://api.slack.com/methods/chat.postMessage
[slack-chat-sch]: https://api.slack.com/methods/chat.scheduleMessage
[slack-chat-sch-list]: https://api.slack.com/methods/chat.scheduledMessages.list

**Comment by khaledmashaly** [comment]
@abuaboud Do you think this is OK to start the implementation?

**Comment by abuaboud** [comment]
Looks great, Thank you Khaled!
